@echo off
echo Starting Dental Chart Application...
echo.
echo Starting backend server...
start "Backend Server" cmd /k "npm run server"
timeout /t 3 /nobreak > nul
echo Starting frontend client...
start "Frontend Client" cmd /k "npm run client"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
pause